spring:
  application:
    name: sensordata
  datasource:
    url: jdbc:postgresql://localhost:5432/sensordb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: sensor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org:
      hibernate:
        sql: DEBUG
        type: TRACE
      springframework:
        kafka: DEBUG
      kafka: DEBUG